FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY client/package*.json client/
COPY server/package*.json server/
COPY clock-client/package*.json clock-client/
RUN npm ci

COPY client client
COPY shared shared
RUN npm run build --workspace=client

FROM nginx:1.27-alpine
COPY --from=builder /app/client/dist /usr/share/nginx/html
COPY deployment/synology/nginx/client.nginx.conf /etc/nginx/conf.d/default.conf
RUN chmod -R u=rwX,go=rX /usr/share/nginx/html
