export const DEFAULT_INSTALL_ESTIMATOR_SETTINGS = {
  name: "Default Install Estimator",
  is_default: true,
  is_active: true,
  base_install_hours: 2,
  hours_per_cabinet: 1.15,
  hours_per_drawer: 0.3,
  hours_per_door_front: 0.18,
  hours_per_tall_unit: 0.85,
  hours_per_panel: 0.2,
  hours_per_hardware_accessory_item: 0.05,
  hours_per_benchtop_item: 1.5,
  hours_per_subcontract_item: 0.5,
  manual_scope_adjustment_hours: 0,
  minimum_duration_hours: 4,
  rounding_rule: "nearest_half_day",
  default_complexity: "standard",
  crew_size_two_person_hours: 10.5,
  crew_size_three_person_hours: 21,
  crew_size_four_person_hours: 31.5,
};
