import { EntityData, LocalUser } from "./types";

export interface SeedEntityRecord {
  entity: string;
  record: EntityData;
}

const now = new Date();

function isoDateOffset(days: number) {
  return new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();
}

function dateOnlyOffset(days: number) {
  return isoDateOffset(days).split("T")[0];
}

export const LOCAL_USER: LocalUser = {
  id: "local-admin",
  full_name: "Local Admin",
  role: "admin",
  email: "admin@joinerflow.local",
};

export const seedRecords: SeedEntityRecord[] = [
  {
    entity: "LeadCategory",
    record: {
      id: "lead-category-general",
      name: "General enquiry",
      key: "general_enquiry",
      color: "blue",
      sort_order: 0,
      is_default: true,
      is_active: true,
      created_date: isoDateOffset(-90),
    },
  },
  {
    entity: "LeadCategory",
    record: {
      id: "lead-category-kitchen",
      name: "Kitchen",
      key: "kitchen",
      color: "amber",
      sort_order: 1,
      is_default: false,
      is_active: true,
      created_date: isoDateOffset(-90),
    },
  },
  {
    entity: "LeadCategory",
    record: {
      id: "lead-category-wardrobe",
      name: "Wardrobe",
      key: "wardrobe",
      color: "purple",
      sort_order: 2,
      is_default: false,
      is_active: true,
      created_date: isoDateOffset(-90),
    },
  },
  {
    entity: "LeadCategory",
    record: {
      id: "lead-category-commercial",
      name: "Commercial",
      key: "commercial",
      color: "teal",
      sort_order: 3,
      is_default: false,
      is_active: true,
      created_date: isoDateOffset(-90),
    },
  },
  {
    entity: "Company",
    record: {
      id: "company-harbour",
      name: "Harbour Homes",
      type: "builder",
      email: "projects@harbourhomes.local",
      phone: "09 555 0101",
      city: "Auckland",
      state: "Auckland",
      status: "active",
      created_date: isoDateOffset(-45),
    },
  },
  {
    entity: "Company",
    record: {
      id: "company-atelier",
      name: "Atelier Interior Studio",
      type: "designer",
      email: "hello@atelier.local",
      phone: "09 555 0112",
      city: "Auckland",
      state: "Auckland",
      status: "active",
      created_date: isoDateOffset(-38),
    },
  },
  {
    entity: "Company",
    record: {
      id: "company-northshore",
      name: "Northshore Offices",
      type: "client",
      email: "facilities@northshore.local",
      phone: "09 555 0127",
      city: "Takapuna",
      state: "Auckland",
      status: "active",
      created_date: isoDateOffset(-30),
    },
  },
  {
    entity: "Contact",
    record: {
      id: "contact-jane",
      first_name: "Jane",
      last_name: "Fletcher",
      title: "Senior Project Coordinator",
      role: "Builder liaison",
      company_id: "company-harbour",
      company_name: "Harbour Homes",
      type: "builder",
      email: "jane.fletcher@harbourhomes.local",
      phone: "021 111 1111",
      owner: "Ella Bennett",
      relationship_status: "active",
      preferred_channel: "phone",
      last_contacted_date: dateOnlyOffset(-2),
      next_follow_up_date: dateOnlyOffset(3),
      is_primary: true,
      tags: ["builder", "kitchen", "priority"],
      status: "active",
      created_date: isoDateOffset(-45),
    },
  },
  {
    entity: "Contact",
    record: {
      id: "contact-sophia",
      first_name: "Sophia",
      last_name: "Ngata",
      title: "Lead Designer",
      role: "Design partner",
      company_id: "company-atelier",
      company_name: "Atelier Interior Studio",
      type: "designer",
      email: "sophia@atelier.local",
      phone: "021 222 2222",
      owner: "Lily Chen",
      relationship_status: "champion",
      preferred_channel: "email",
      last_contacted_date: dateOnlyOffset(-1),
      next_follow_up_date: dateOnlyOffset(7),
      is_primary: true,
      tags: ["design", "vip"],
      status: "active",
      created_date: isoDateOffset(-38),
    },
  },
  {
    entity: "Contact",
    record: {
      id: "contact-daniel",
      first_name: "Daniel",
      last_name: "Brooks",
      title: "Facilities Manager",
      role: "Decision maker",
      company_id: "company-northshore",
      company_name: "Northshore Offices",
      type: "client",
      email: "daniel@northshore.local",
      phone: "021 333 3333",
      owner: "Ella Bennett",
      relationship_status: "customer",
      preferred_channel: "email",
      last_contacted_date: dateOnlyOffset(-18),
      next_follow_up_date: dateOnlyOffset(-1),
      is_primary: true,
      tags: ["commercial", "office"],
      status: "active",
      created_date: isoDateOffset(-30),
    },
  },
  {
    entity: "ContactTask",
    record: {
      id: "contacttask-jane-follow-up",
      contact_id: "contact-jane",
      title: "Call Jane to confirm revised appliance schedule",
      due_date: dateOnlyOffset(3),
      assigned_to: "Ella Bennett",
      status: "pending",
      priority: "high",
      type: "call",
      created_date: isoDateOffset(-1),
    },
  },
  {
    entity: "ContactTask",
    record: {
      id: "contacttask-daniel-checkin",
      contact_id: "contact-daniel",
      title: "Send follow-up after lost tender review",
      due_date: dateOnlyOffset(-1),
      assigned_to: "Ella Bennett",
      status: "pending",
      priority: "medium",
      type: "email",
      created_date: isoDateOffset(-5),
    },
  },
  {
    entity: "ContactInteraction",
    record: {
      id: "contactinteraction-jane-call",
      contact_id: "contact-jane",
      type: "call",
      direction: "outbound",
      visibility: "internal",
      subject: "Confirmed measure date",
      summary: "Locked in Thursday morning site measure and updated the builder on the sink lead time.",
      interaction_date: isoDateOffset(-2),
      next_step_date: dateOnlyOffset(3),
      created_date: isoDateOffset(-2),
    },
  },
  {
    entity: "ContactInteraction",
    record: {
      id: "contactinteraction-sophia-email",
      contact_id: "contact-sophia",
      type: "email",
      direction: "inbound",
      visibility: "internal",
      subject: "Penthouse finish selections approved",
      summary: "Sophia approved the oak finish sample set and requested the wardrobe internals stay on the current timeline.",
      interaction_date: isoDateOffset(-1),
      created_date: isoDateOffset(-1),
    },
  },
  {
    entity: "ContactInteraction",
    record: {
      id: "contactinteraction-daniel-meeting",
      contact_id: "contact-daniel",
      type: "meeting",
      direction: "outbound",
      visibility: "internal",
      subject: "Reception desk post-tender review",
      summary: "Reviewed why the project did not proceed and identified a smaller stage-two opportunity later this quarter.",
      interaction_date: isoDateOffset(-18),
      next_step_date: dateOnlyOffset(-1),
      created_date: isoDateOffset(-18),
    },
  },
  {
    entity: "Staff",
    record: {
      id: "staff-jamie-mcanulty",
      name: "McAnulty, Jamie",
      employee_id: "EMP001",
      phone: "0272480404",
      staff_type: "Employee",
      email: "",
      hourly_rate: 52,
      status: "active",
      created_date: isoDateOffset(-80),
    },
  },
  {
    entity: "Staff",
    record: {
      id: "staff-richard-constance",
      name: "Constance, Richard",
      employee_id: "EMP002",
      phone: "0272503559",
      staff_type: "Employee",
      email: "",
      hourly_rate: 48,
      status: "active",
      created_date: isoDateOffset(-80),
    },
  },
  {
    entity: "Staff",
    record: {
      id: "staff-bruce-drummond",
      name: "Drummond, Bruce",
      employee_id: "EMP003",
      phone: "",
      staff_type: "Employee",
      email: "",
      hourly_rate: 60,
      status: "active",
      created_date: isoDateOffset(-75),
    },
  },
  {
    entity: "Staff",
    record: {
      id: "staff-mathew-drummond",
      name: "Drummond, Mathew",
      employee_id: "EMP004",
      phone: "",
      staff_type: "Employee",
      email: "",
      hourly_rate: 0,
      status: "active",
      created_date: isoDateOffset(-75),
    },
  },
  {
    entity: "Supplier",
    record: {
      id: "supplier-boardworks",
      name: "BoardWorks NZ",
      contact_name: "Mike Rangi",
      email: "sales@boardworks.local",
      phone: "09 555 0201",
      category: "board_supplier",
      payment_terms: "30_days",
      status: "active",
      created_date: isoDateOffset(-60),
    },
  },
  {
    entity: "Supplier",
    record: {
      id: "supplier-fitfast",
      name: "FitFast Hardware",
      contact_name: "Amy Hart",
      email: "orders@fitfast.local",
      phone: "09 555 0209",
      category: "hardware",
      payment_terms: "14_days",
      status: "active",
      created_date: isoDateOffset(-55),
    },
  },
  {
    entity: "Company",
    record: {
      id: "company-supplier-boardworks",
      name: "BoardWorks NZ",
      type: "supplier",
      email: "sales@boardworks.local",
      phone: "09 555 0201",
      city: "Auckland",
      state: "Auckland",
      status: "active",
      created_date: isoDateOffset(-60),
    },
  },
  {
    entity: "Company",
    record: {
      id: "company-supplier-fitfast",
      name: "FitFast Hardware",
      type: "supplier",
      email: "orders@fitfast.local",
      phone: "09 555 0209",
      city: "Auckland",
      state: "Auckland",
      status: "active",
      created_date: isoDateOffset(-55),
    },
  },
  {
    entity: "Lead",
    record: {
      id: "lead-riverside",
      title: "Riverside townhouse kitchen",
      contact_id: "contact-jane",
      contact_name: "Jane Fletcher",
      company_id: "company-harbour",
      company_name: "Harbour Homes",
      category_id: "lead-category-kitchen",
      stage: "quote_in_progress",
      value: 42000,
      probability: 65,
      expected_close: dateOnlyOffset(10),
      source: "referral",
      assigned_to: "Ella Bennett",
      description: "Custom kitchen and laundry package for Lot 12.",
      site_address: "12 Riverside Lane, Auckland",
      priority: "high",
      created_date: isoDateOffset(-12),
    },
  },
  {
    entity: "Lead",
    record: {
      id: "lead-penthouse",
      title: "Ponsonby penthouse fit-out",
      contact_id: "contact-sophia",
      contact_name: "Sophia Ngata",
      company_id: "company-atelier",
      company_name: "Atelier Interior Studio",
      category_id: "lead-category-commercial",
      stage: "won",
      value: 98000,
      probability: 100,
      expected_close: dateOnlyOffset(-7),
      source: "repeat_client",
      assigned_to: "Lily Chen",
      description: "Full apartment joinery package including wardrobes and media wall.",
      site_address: "22 Franklin Road, Auckland",
      priority: "urgent",
      created_date: isoDateOffset(-34),
    },
  },
  {
    entity: "Lead",
    record: {
      id: "lead-northshore",
      title: "Northshore office reception",
      contact_id: "contact-daniel",
      contact_name: "Daniel Brooks",
      company_id: "company-northshore",
      company_name: "Northshore Offices",
      category_id: "lead-category-commercial",
      stage: "lost",
      value: 18500,
      probability: 0,
      expected_close: dateOnlyOffset(-18),
      source: "website",
      assigned_to: "Ella Bennett",
      description: "Reception desk and acoustic wall panels.",
      site_address: "8 Huron Street, Takapuna",
      priority: "medium",
      lost_reason: "Budget moved to another contractor",
      created_date: isoDateOffset(-26),
    },
  },
  {
    entity: "LeadTask",
    record: {
      id: "leadtask-riverside-measure",
      lead_id: "lead-riverside",
      title: "Confirm final site measure",
      due_date: dateOnlyOffset(2),
      assigned_to: "Ella Bennett",
      status: "pending",
      priority: "high",
      type: "measure",
      created_date: isoDateOffset(-2),
    },
  },
  {
    entity: "Note",
    record: {
      id: "note-lead-riverside",
      content: "Builder wants cabinetry drawings aligned with revised plumbing plan.",
      related_id: "lead-riverside",
      related_type: "lead",
      type: "note",
      author_name: LOCAL_USER.full_name,
      created_date: isoDateOffset(-1),
    },
  },
  {
    entity: "Quote",
    record: {
      id: "quote-riverside",
      quote_number: "QTE-0001",
      title: "Riverside townhouse kitchen",
      lead_id: "lead-riverside",
      contact_id: "contact-jane",
      contact_name: "Jane Fletcher",
      company_id: "company-harbour",
      company_name: "Harbour Homes",
      status: "draft",
      revision: 1,
      subtotal: 38200,
      gst: 3820,
      total: 42020,
      valid_until: dateOnlyOffset(20),
      assigned_to: "Ella Bennett",
      site_address: "12 Riverside Lane, Auckland",
      approval_status: "pending_internal",
      approval_owner: "Bruce Millbrook",
      approval_requested_date: dateOnlyOffset(-1),
      quote_scope_signed_off: true,
      quote_drawings_signed_off: true,
      quote_pricing_signed_off: false,
      quote_client_brief_signed_off: true,
      production_handoff_status: "not_ready",
      quote_internal_notes: "Pricing still needs bought-out appliance allowance confirmed.",
      job_conversion_notes: "Do not release to workshop until stone lead times are reconfirmed.",
      change_orders: [
        {
          id: "co-quote-riverside-1",
          title: "Laundry tall unit added",
          amount: 2800,
          status: "awaiting_approval",
          requested_by: "Jane Fletcher",
          requested_date: dateOnlyOffset(-1),
          impact: "Adds one extra fabrication day.",
          notes: "Awaiting builder sign-off on revised joinery scope.",
        },
      ],
      created_date: isoDateOffset(-6),
    },
  },
  {
    entity: "Quote",
    record: {
      id: "quote-penthouse",
      quote_number: "QTE-0002",
      title: "Ponsonby penthouse fit-out",
      lead_id: "lead-penthouse",
      contact_id: "contact-sophia",
      contact_name: "Sophia Ngata",
      company_id: "company-atelier",
      company_name: "Atelier Interior Studio",
      status: "accepted",
      revision: 2,
      subtotal: 89000,
      gst: 8900,
      total: 97900,
      valid_until: dateOnlyOffset(-12),
      assigned_to: "Lily Chen",
      site_address: "22 Franklin Road, Auckland",
      approval_status: "approved",
      approval_owner: "Mathew Collins",
      approval_requested_date: dateOnlyOffset(-30),
      approval_completed_date: dateOnlyOffset(-28),
      approval_history: [
        {
          id: "approval-quote-penthouse-1",
          status: "approved",
          actor: "Mathew Collins",
          note: "Approved after revision 2 margin review.",
          date: isoDateOffset(-28),
        },
      ],
      quote_scope_signed_off: true,
      quote_drawings_signed_off: true,
      quote_pricing_signed_off: true,
      quote_client_brief_signed_off: true,
      production_handoff_status: "ready",
      created_date: isoDateOffset(-28),
    },
  },
  {
    entity: "QuoteItem",
    record: {
      id: "quoteitem-riverside-cabinets",
      quote_id: "quote-riverside",
      section: "Kitchen",
      description: "Custom oak veneer cabinetry",
      category: "materials",
      quantity: 1,
      unit: "lot",
      unit_cost: 18000,
      markup_percent: 35,
      sell_price: 24300,
      total: 24300,
      sort_order: 0,
      created_date: isoDateOffset(-6),
    },
  },
  {
    entity: "QuoteItem",
    record: {
      id: "quoteitem-riverside-labour",
      quote_id: "quote-riverside",
      section: "Installation",
      description: "Fabrication and installation labour",
      category: "labour",
      quantity: 80,
      unit: "hr",
      unit_cost: 95,
      markup_percent: 20,
      sell_price: 114,
      total: 9120,
      sort_order: 1,
      created_date: isoDateOffset(-6),
    },
  },
  {
    entity: "QuoteItem",
    record: {
      id: "quoteitem-riverside-hardware",
      quote_id: "quote-riverside",
      section: "Hardware",
      description: "Soft-close drawer hardware package",
      category: "hardware",
      quantity: 1,
      unit: "set",
      unit_cost: 3500,
      markup_percent: 18,
      sell_price: 4130,
      total: 4130,
      sort_order: 2,
      created_date: isoDateOffset(-6),
    },
  },
  {
    entity: "Job",
    record: {
      id: "job-penthouse",
      job_number: "JOB-0001",
      title: "Ponsonby penthouse fit-out",
      job_name: "Penthouse Fit-out",
      client: "Atelier Interior Studio",
      quote_id: "quote-penthouse",
      lead_id: "lead-penthouse",
      contact_id: "contact-sophia",
      contact_name: "Sophia Ngata",
      company_id: "company-atelier",
      company_name: "Atelier Interior Studio",
      status: "production",
      quoted_value: 97900,
      site_address: "22 Franklin Road, Auckland",
      salesperson: "Lily Chen",
      project_manager: "Lily Chen",
      designer: "Ella Bennett",
      start_date: dateOnlyOffset(-14),
      due_date: dateOnlyOffset(12),
      install_date: dateOnlyOffset(18),
      priority: "urgent",
      approval_status: "approved",
      approval_owner: "Lily Chen",
      approval_requested_date: dateOnlyOffset(-16),
      approval_completed_date: dateOnlyOffset(-15),
      approval_history: [
        {
          id: "approval-job-penthouse-1",
          status: "approved",
          actor: "Lily Chen",
          note: "Released to pre-production once final drawings landed.",
          date: isoDateOffset(-15),
        },
      ],
      procurement_status: "in_progress",
      procurement_takeoff_complete: true,
      procurement_supplier_confirmed: true,
      procurement_pos_raised: true,
      procurement_critical_items_received: false,
      procurement_notes: "Stone benchtop still on supplier confirmation.",
      handoff_status: "in_progress",
      handoff_site_measure_complete: true,
      handoff_drawings_ready: true,
      handoff_materials_confirmed: true,
      handoff_production_brief_complete: false,
      handoff_install_plan_confirmed: false,
      handoff_notes: "Lift access and install sequence still need final confirmation.",
      internal_operational_notes: "Workshop to keep wardrobe carcasses modular for lift size.",
      change_orders: [
        {
          id: "co-job-penthouse-1",
          title: "Master wardrobe LED shelf detail",
          amount: 3200,
          status: "approved",
          requested_by: "Sophia Ngata",
          requested_date: dateOnlyOffset(-10),
          impact: "Requires updated wiring prep before install.",
          notes: "Approved by designer and client on site.",
        },
      ],
      created_date: isoDateOffset(-20),
    },
  },
  {
    entity: "Job",
    record: {
      id: "job-studio",
      job_number: "JOB-0002",
      title: "Atelier sample studio cabinetry",
      job_name: "Sample Studio",
      client: "Atelier Interior Studio",
      contact_id: "contact-sophia",
      contact_name: "Sophia Ngata",
      company_id: "company-atelier",
      company_name: "Atelier Interior Studio",
      status: "ready_to_install",
      quoted_value: 26400,
      site_address: "6 Mackelvie Street, Ponsonby",
      salesperson: "Ella Bennett",
      project_manager: "Noah Kumar",
      start_date: dateOnlyOffset(-5),
      due_date: dateOnlyOffset(5),
      install_date: dateOnlyOffset(7),
      priority: "medium",
      approval_status: "approved",
      procurement_status: "ready",
      procurement_takeoff_complete: true,
      procurement_supplier_confirmed: true,
      procurement_pos_raised: false,
      procurement_critical_items_received: false,
      handoff_status: "ready",
      handoff_site_measure_complete: true,
      handoff_drawings_ready: true,
      handoff_materials_confirmed: true,
      handoff_production_brief_complete: true,
      handoff_install_plan_confirmed: true,
      created_date: isoDateOffset(-10),
    },
  },
  {
    entity: "JobOperation",
    record: {
      id: "jobop-penthouse-design",
      job_id: "job-penthouse",
      job_number: "JOB-0001",
      job_title: "Ponsonby penthouse fit-out",
      operation: "design",
      status: "completed",
      assigned_to: "Ella Bennett",
      start_date: dateOnlyOffset(-18),
      end_date: dateOnlyOffset(-14),
      estimated_hours: 18,
      actual_hours: 20,
      sort_order: 0,
      created_date: isoDateOffset(-18),
    },
  },
  {
    entity: "JobOperation",
    record: {
      id: "jobop-penthouse-assembly",
      job_id: "job-penthouse",
      job_number: "JOB-0001",
      job_title: "Ponsonby penthouse fit-out",
      operation: "assembly",
      status: "in_progress",
      assigned_to: "Noah Kumar",
      start_date: dateOnlyOffset(-2),
      end_date: dateOnlyOffset(2),
      estimated_hours: 36,
      actual_hours: 14,
      sort_order: 1,
      created_date: isoDateOffset(-4),
    },
  },
  {
    entity: "JobOperation",
    record: {
      id: "jobop-studio-install",
      job_id: "job-studio",
      job_number: "JOB-0002",
      job_title: "Atelier sample studio cabinetry",
      operation: "install",
      status: "scheduled",
      assigned_to: "Lily Chen",
      start_date: dateOnlyOffset(7),
      end_date: dateOnlyOffset(8),
      estimated_hours: 16,
      actual_hours: 0,
      sort_order: 0,
      created_date: isoDateOffset(-1),
    },
  },
  {
    entity: "TimeEntry",
    record: {
      id: "time-penthouse-design",
      staff_id: "staff-jamie-mcanulty",
      staff_name: "McAnulty, Jamie",
      employee_id: "EMP001",
      staff_email: "",
      job_id: "job-penthouse",
      job_number: "JOB-0001",
      job_title: "Ponsonby penthouse fit-out",
      operation: "design",
      clock_in: isoDateOffset(-17),
      clock_out: isoDateOffset(-17 + 0.3),
      hours: 7.5,
      hourly_rate: 52,
      total_cost: 390,
      status: "completed",
      notes: "Finalised appliance wall details",
      date: dateOnlyOffset(-17),
      exported: true,
      exported_batch_id: "batch-001",
      created_date: isoDateOffset(-17),
    },
  },
  {
    entity: "TimeEntry",
    record: {
      id: "time-penthouse-assembly",
      staff_id: "staff-richard-constance",
      staff_name: "Constance, Richard",
      employee_id: "EMP002",
      staff_email: "",
      job_id: "job-penthouse",
      job_number: "JOB-0001",
      job_title: "Ponsonby penthouse fit-out",
      operation: "assembly",
      clock_in: isoDateOffset(-2),
      clock_out: isoDateOffset(-2 + 0.33),
      hours: 8,
      hourly_rate: 48,
      total_cost: 384,
      status: "completed",
      notes: "Assembled wardrobe carcasses",
      date: dateOnlyOffset(-2),
      exported: false,
      created_date: isoDateOffset(-2),
    },
  },
  {
    entity: "TimeEntry",
    record: {
      id: "time-studio-install-prep",
      staff_id: "staff-bruce-drummond",
      staff_name: "Drummond, Bruce",
      employee_id: "EMP003",
      staff_email: "",
      job_id: "job-studio",
      job_number: "JOB-0002",
      job_title: "Atelier sample studio cabinetry",
      operation: "install",
      clock_in: isoDateOffset(-1),
      clock_out: isoDateOffset(-1 + 0.25),
      hours: 6,
      hourly_rate: 60,
      total_cost: 360,
      status: "completed",
      notes: "Pre-install site prep and check measure",
      date: dateOnlyOffset(-1),
      exported: false,
      created_date: isoDateOffset(-1),
    },
  },
  {
    entity: "ExportHistory",
    record: {
      id: "export-history-001",
      batch_id: "batch-001",
      exported_at: isoDateOffset(-10),
      exported_by: LOCAL_USER.email,
      export_type: "activity_slip",
      time_entry_id: "time-penthouse-design",
      staff_name: "McAnulty, Jamie",
      employee_id: "EMP001",
      job_number: "JOB-0001",
      job_name: "Ponsonby penthouse fit-out",
      activity: "design",
      date: dateOnlyOffset(-17),
      hours: 7.5,
      description: "Finalised appliance wall details",
      created_date: isoDateOffset(-10),
    },
  },
  {
    entity: "Note",
    record: {
      id: "note-job-penthouse",
      content: "Installation sequencing depends on lift access confirmation from the building manager.",
      related_id: "job-penthouse",
      related_type: "job",
      type: "note",
      author_name: LOCAL_USER.full_name,
      created_date: isoDateOffset(-3),
    },
  },
];
