export const UI_COMPONENT_CATALOG_CATEGORIES = [
  "action",
  "data-display",
  "feedback",
  "form",
  "layout",
  "navigation",
  "overlay",
  "surface",
  "utility",
];

export const uiComponentCatalog = [
  {
    id: "accordion",
    file: "accordion.jsx",
    category: "surface",
    owner: "design-system",
    exports: ["Accordion", "AccordionItem", "AccordionTrigger", "AccordionContent"],
    purpose: "Expandable content sections for dense operational screens.",
  },
  {
    id: "alert",
    file: "alert.jsx",
    category: "feedback",
    owner: "design-system",
    exports: ["Alert", "AlertTitle", "AlertDescription"],
    purpose: "Inline status and validation messaging.",
  },
  {
    id: "alert-dialog",
    file: "alert-dialog.jsx",
    category: "overlay",
    owner: "design-system",
    exports: [
      "AlertDialog",
      "AlertDialogAction",
      "AlertDialogCancel",
      "AlertDialogContent",
      "AlertDialogDescription",
      "AlertDialogFooter",
      "AlertDialogHeader",
      "AlertDialogOverlay",
      "AlertDialogPortal",
      "AlertDialogTitle",
      "AlertDialogTrigger",
    ],
    purpose: "Confirmation dialogs for destructive or irreversible actions.",
  },
  {
    id: "aspect-ratio",
    file: "aspect-ratio.jsx",
    category: "layout",
    owner: "design-system",
    exports: ["AspectRatio"],
    purpose: "Stable media and preview sizing.",
  },
  {
    id: "avatar",
    file: "avatar.jsx",
    category: "data-display",
    owner: "design-system",
    exports: ["Avatar", "AvatarImage", "AvatarFallback"],
    purpose: "User or staff identity thumbnails.",
  },
  {
    id: "badge",
    file: "badge.jsx",
    category: "feedback",
    owner: "design-system",
    exports: ["Badge", "badgeVariants"],
    purpose: "Compact state, role, and category labels.",
  },
  {
    id: "breadcrumb",
    file: "breadcrumb.jsx",
    category: "navigation",
    owner: "design-system",
    exports: [
      "Breadcrumb",
      "BreadcrumbEllipsis",
      "BreadcrumbItem",
      "BreadcrumbLink",
      "BreadcrumbList",
      "BreadcrumbPage",
      "BreadcrumbSeparator",
    ],
    purpose: "Hierarchical page navigation.",
  },
  {
    id: "button",
    file: "button.jsx",
    category: "action",
    owner: "design-system",
    exports: ["Button", "buttonVariants"],
    purpose: "Primary command primitive for forms, toolbars, and dialogs.",
  },
  {
    id: "calendar",
    file: "calendar.jsx",
    category: "form",
    owner: "design-system",
    exports: ["Calendar"],
    purpose: "Date picking inside popovers and schedule controls.",
  },
  {
    id: "card",
    file: "card.jsx",
    category: "surface",
    owner: "design-system",
    exports: ["Card", "CardHeader", "CardFooter", "CardTitle", "CardDescription", "CardContent"],
    purpose: "Framed repeated content and compact panels.",
  },
  {
    id: "carousel",
    file: "carousel.jsx",
    category: "navigation",
    owner: "design-system",
    exports: ["Carousel", "CarouselContent", "CarouselItem", "CarouselPrevious", "CarouselNext"],
    purpose: "Horizontal item browsing where content order matters.",
  },
  {
    id: "chart",
    file: "chart.jsx",
    category: "data-display",
    owner: "design-system",
    exports: ["ChartContainer", "ChartTooltip", "ChartTooltipContent", "ChartLegend", "ChartLegendContent", "ChartStyle"],
    purpose: "Shared chart container, tooltip, and legend styling.",
  },
  {
    id: "checkbox",
    file: "checkbox.jsx",
    category: "form",
    owner: "design-system",
    exports: ["Checkbox"],
    purpose: "Binary or multi-select form control.",
  },
  {
    id: "collapsible",
    file: "collapsible.jsx",
    category: "surface",
    owner: "design-system",
    exports: ["Collapsible", "CollapsibleTrigger", "CollapsibleContent"],
    purpose: "Expandable local disclosure regions.",
  },
  {
    id: "command",
    file: "command.jsx",
    category: "form",
    owner: "design-system",
    exports: [
      "Command",
      "CommandDialog",
      "CommandInput",
      "CommandList",
      "CommandEmpty",
      "CommandGroup",
      "CommandItem",
      "CommandShortcut",
      "CommandSeparator",
    ],
    purpose: "Searchable command and picker surfaces.",
  },
  {
    id: "context-menu",
    file: "context-menu.jsx",
    category: "overlay",
    owner: "design-system",
    exports: [
      "ContextMenu",
      "ContextMenuTrigger",
      "ContextMenuContent",
      "ContextMenuItem",
      "ContextMenuCheckboxItem",
      "ContextMenuRadioItem",
      "ContextMenuLabel",
      "ContextMenuSeparator",
      "ContextMenuShortcut",
      "ContextMenuGroup",
      "ContextMenuPortal",
      "ContextMenuSub",
      "ContextMenuSubContent",
      "ContextMenuSubTrigger",
      "ContextMenuRadioGroup",
    ],
    purpose: "Secondary actions scoped to selected records or UI regions.",
  },
  {
    id: "dialog",
    file: "dialog.jsx",
    category: "overlay",
    owner: "design-system",
    exports: [
      "Dialog",
      "DialogPortal",
      "DialogOverlay",
      "DialogTrigger",
      "DialogClose",
      "DialogContent",
      "DialogHeader",
      "DialogFooter",
      "DialogTitle",
      "DialogDescription",
    ],
    purpose: "Modal workflows and focused editing surfaces.",
  },
  {
    id: "drawer",
    file: "drawer.jsx",
    category: "overlay",
    owner: "design-system",
    exports: [
      "Drawer",
      "DrawerPortal",
      "DrawerOverlay",
      "DrawerTrigger",
      "DrawerClose",
      "DrawerContent",
      "DrawerHeader",
      "DrawerFooter",
      "DrawerTitle",
      "DrawerDescription",
    ],
    purpose: "Slide-in mobile and detail workflows.",
  },
  {
    id: "dropdown-menu",
    file: "dropdown-menu.jsx",
    category: "overlay",
    owner: "design-system",
    exports: [
      "DropdownMenu",
      "DropdownMenuTrigger",
      "DropdownMenuContent",
      "DropdownMenuItem",
      "DropdownMenuCheckboxItem",
      "DropdownMenuRadioItem",
      "DropdownMenuLabel",
      "DropdownMenuSeparator",
      "DropdownMenuShortcut",
      "DropdownMenuGroup",
      "DropdownMenuPortal",
      "DropdownMenuSub",
      "DropdownMenuSubContent",
      "DropdownMenuSubTrigger",
      "DropdownMenuRadioGroup",
    ],
    purpose: "Compact action menus and option lists.",
  },
  {
    id: "form",
    file: "form.jsx",
    category: "form",
    owner: "design-system",
    exports: ["Form", "FormItem", "FormLabel", "FormControl", "FormDescription", "FormMessage", "FormField", "useFormField"],
    purpose: "React Hook Form wiring and accessible field messaging.",
  },
  {
    id: "hover-card",
    file: "hover-card.jsx",
    category: "overlay",
    owner: "design-system",
    exports: ["HoverCard", "HoverCardTrigger", "HoverCardContent"],
    purpose: "Supplementary hover/focus context.",
  },
  {
    id: "input",
    file: "input.jsx",
    category: "form",
    owner: "design-system",
    exports: ["Input"],
    purpose: "Single-line text and numeric input.",
  },
  {
    id: "input-otp",
    file: "input-otp.jsx",
    category: "form",
    owner: "design-system",
    exports: ["InputOTP", "InputOTPGroup", "InputOTPSlot", "InputOTPSeparator"],
    purpose: "Segmented code entry.",
  },
  {
    id: "label",
    file: "label.jsx",
    category: "form",
    owner: "design-system",
    exports: ["Label"],
    purpose: "Accessible form labels.",
  },
  {
    id: "menubar",
    file: "menubar.jsx",
    category: "navigation",
    owner: "design-system",
    exports: [
      "Menubar",
      "MenubarMenu",
      "MenubarTrigger",
      "MenubarContent",
      "MenubarItem",
      "MenubarSeparator",
      "MenubarLabel",
      "MenubarCheckboxItem",
      "MenubarRadioGroup",
      "MenubarRadioItem",
      "MenubarPortal",
      "MenubarSubContent",
      "MenubarSubTrigger",
      "MenubarGroup",
      "MenubarSub",
      "MenubarShortcut",
    ],
    purpose: "Application-style menu navigation.",
  },
  {
    id: "navigation-menu",
    file: "navigation-menu.jsx",
    category: "navigation",
    owner: "design-system",
    exports: [
      "NavigationMenu",
      "NavigationMenuList",
      "NavigationMenuItem",
      "NavigationMenuContent",
      "NavigationMenuTrigger",
      "NavigationMenuLink",
      "NavigationMenuIndicator",
      "NavigationMenuViewport",
      "navigationMenuTriggerStyle",
    ],
    purpose: "Top-level navigation menu composition.",
  },
  {
    id: "on-screen-keyboard",
    file: "OnScreenKeyboard.jsx",
    category: "form",
    owner: "timeclock",
    exports: ["OnScreenKeyboard"],
    purpose: "Touch-friendly numeric keyboard for kiosk/timeclock entry.",
  },
  {
    id: "pagination",
    file: "pagination.jsx",
    category: "navigation",
    owner: "design-system",
    exports: [
      "Pagination",
      "PaginationContent",
      "PaginationEllipsis",
      "PaginationItem",
      "PaginationLink",
      "PaginationNext",
      "PaginationPrevious",
    ],
    purpose: "Paged record navigation.",
  },
  {
    id: "popover",
    file: "popover.jsx",
    category: "overlay",
    owner: "design-system",
    exports: ["Popover", "PopoverTrigger", "PopoverContent", "PopoverAnchor"],
    purpose: "Anchored lightweight overlays for pickers and controls.",
  },
  {
    id: "progress",
    file: "progress.jsx",
    category: "feedback",
    owner: "design-system",
    exports: ["Progress"],
    purpose: "Progress indication for known-length work.",
  },
  {
    id: "radio-group",
    file: "radio-group.jsx",
    category: "form",
    owner: "design-system",
    exports: ["RadioGroup", "RadioGroupItem"],
    purpose: "Single choice selection groups.",
  },
  {
    id: "resizable",
    file: "resizable.jsx",
    category: "layout",
    owner: "design-system",
    exports: ["ResizablePanelGroup", "ResizablePanel", "ResizableHandle"],
    purpose: "User-adjustable split panels.",
  },
  {
    id: "scroll-area",
    file: "scroll-area.jsx",
    category: "layout",
    owner: "design-system",
    exports: ["ScrollArea", "ScrollBar"],
    purpose: "Styled scroll containers for constrained panes.",
  },
  {
    id: "select",
    file: "select.jsx",
    category: "form",
    owner: "design-system",
    exports: [
      "Select",
      "SelectGroup",
      "SelectValue",
      "SelectTrigger",
      "SelectContent",
      "SelectLabel",
      "SelectItem",
      "SelectSeparator",
      "SelectScrollUpButton",
      "SelectScrollDownButton",
    ],
    purpose: "Single value option selection.",
  },
  {
    id: "separator",
    file: "separator.jsx",
    category: "layout",
    owner: "design-system",
    exports: ["Separator"],
    purpose: "Visual grouping divider.",
  },
  {
    id: "sheet",
    file: "sheet.jsx",
    category: "overlay",
    owner: "design-system",
    exports: ["Sheet", "SheetPortal", "SheetOverlay", "SheetTrigger", "SheetClose", "SheetContent", "SheetHeader", "SheetFooter", "SheetTitle", "SheetDescription"],
    purpose: "Side-panel overlays for contextual workflows.",
  },
  {
    id: "sidebar",
    file: "sidebar.jsx",
    category: "navigation",
    owner: "design-system",
    exports: [
      "Sidebar",
      "SidebarContent",
      "SidebarFooter",
      "SidebarGroup",
      "SidebarGroupAction",
      "SidebarGroupContent",
      "SidebarGroupLabel",
      "SidebarHeader",
      "SidebarInput",
      "SidebarInset",
      "SidebarMenu",
      "SidebarMenuAction",
      "SidebarMenuBadge",
      "SidebarMenuButton",
      "SidebarMenuItem",
      "SidebarMenuSkeleton",
      "SidebarMenuSub",
      "SidebarMenuSubButton",
      "SidebarMenuSubItem",
      "SidebarProvider",
      "SidebarRail",
      "SidebarSeparator",
      "SidebarTrigger",
      "useSidebar",
    ],
    purpose: "Application shell side navigation and responsive drawer behavior.",
  },
  {
    id: "skeleton",
    file: "skeleton.jsx",
    category: "feedback",
    owner: "design-system",
    exports: ["Skeleton"],
    purpose: "Loading placeholders that preserve layout.",
  },
  {
    id: "slider",
    file: "slider.jsx",
    category: "form",
    owner: "design-system",
    exports: ["Slider"],
    purpose: "Continuous numeric range input.",
  },
  {
    id: "sonner",
    file: "sonner.jsx",
    category: "feedback",
    owner: "design-system",
    exports: ["Toaster"],
    purpose: "Sonner notification host.",
  },
  {
    id: "sortable-header",
    file: "sortable-header.jsx",
    category: "data-display",
    owner: "design-system",
    exports: ["SortableHeader", "SortableButton"],
    purpose: "Accessible sortable table header controls.",
  },
  {
    id: "switch",
    file: "switch.jsx",
    category: "form",
    owner: "design-system",
    exports: ["Switch"],
    purpose: "Boolean setting toggle.",
  },
  {
    id: "table",
    file: "table.jsx",
    category: "data-display",
    owner: "design-system",
    exports: ["Table", "TableHeader", "TableBody", "TableFooter", "TableHead", "TableRow", "TableCell", "TableCaption"],
    purpose: "Structured tabular record display.",
  },
  {
    id: "tabs",
    file: "tabs.jsx",
    category: "navigation",
    owner: "design-system",
    exports: ["Tabs", "TabsList", "TabsTrigger", "TabsContent"],
    purpose: "Peer view switching within a page or panel.",
  },
  {
    id: "textarea",
    file: "textarea.jsx",
    category: "form",
    owner: "design-system",
    exports: ["Textarea"],
    purpose: "Multi-line text input.",
  },
  {
    id: "toast",
    file: "toast.jsx",
    category: "feedback",
    owner: "design-system",
    exports: ["Toast", "ToastAction", "ToastClose", "ToastDescription", "ToastProvider", "ToastTitle", "ToastViewport"],
    purpose: "Toast notification primitives.",
  },
  {
    id: "toaster",
    file: "toaster.jsx",
    category: "feedback",
    owner: "design-system",
    exports: ["Toaster"],
    purpose: "Application toast notification host.",
  },
  {
    id: "toggle",
    file: "toggle.jsx",
    category: "form",
    owner: "design-system",
    exports: ["Toggle", "toggleVariants"],
    purpose: "Pressed/unpressed control state.",
  },
  {
    id: "toggle-group",
    file: "toggle-group.jsx",
    category: "form",
    owner: "design-system",
    exports: ["ToggleGroup", "ToggleGroupItem"],
    purpose: "Grouped toggle controls for exclusive or multi-select choices.",
  },
  {
    id: "tooltip",
    file: "tooltip.jsx",
    category: "overlay",
    owner: "design-system",
    exports: ["Tooltip", "TooltipTrigger", "TooltipContent", "TooltipProvider"],
    purpose: "Short help for icon-only or compact controls.",
  },
  {
    id: "use-toast",
    file: "use-toast.jsx",
    category: "feedback",
    owner: "design-system",
    exports: ["useToast", "toast", "reducer"],
    purpose: "Toast state and dispatch API.",
  },
];
